"""
Interactive script to help configure your Databricks connection with Azure AD
For JLL organizations that use Azure AD authentication
"""

import os
import sys

def get_input(prompt, default=None, secret=False):
    """Get user input with optional default value"""
    if default:
        prompt_text = f"{prompt} [{default}]: "
    else:
        prompt_text = f"{prompt}: "
    
    if secret:
        import getpass
        value = getpass.getpass(prompt_text)
    else:
        value = input(prompt_text).strip()
    
    return value if value else default

def configure_connection():
    """Interactive configuration helper for Azure AD"""
    print("=" * 60)
    print("JLL EDP Databricks Connection Configuration (Azure AD)")
    print("=" * 60)
    print("\nThis script will help you configure your Databricks connection")
    print("using Azure AD authentication (required for JLL).\n")
    
    input("Press Enter to continue...")
    
    print("\n" + "=" * 60)
    print("STEP 1: Find Your Server Hostname")
    print("=" * 60)
    print("""
1. Open your Databricks workspace in a web browser
2. Look at the URL in your browser's address bar
3. The server hostname is the domain part of the URL

Examples:
   - If URL is: https://adb-1234567890123456.7.azuredatabricks.net
     Server hostname is: adb-1234567890123456.7.azuredatabricks.net
   
   - If URL is: https://your-workspace.cloud.databricks.com
     Server hostname is: your-workspace.cloud.databricks.com
    """)
    
    server_hostname = get_input("Enter your Databricks server hostname")
    
    print("\n" + "=" * 60)
    print("STEP 2: Find Your HTTP Path")
    print("=" * 60)
    print("""
1. In your Databricks workspace, click "SQL Warehouses" in the left sidebar
2. Click on your SQL Warehouse (or create one if you don't have one)
3. Click the "Connection details" tab
4. Copy the "HTTP path" value

Example: /sql/1.0/warehouses/abc123def456ghi789
    """)
    
    http_path = get_input("Enter your HTTP path")
    
    print("\n" + "=" * 60)
    print("STEP 3: Azure AD Authentication Method")
    print("=" * 60)
    print("""
JLL uses Azure AD authentication. Choose your authentication method:

1. Service Principal (Client ID/Secret) - For automated scripts
   - Requires: Azure Client ID, Client Secret, Tenant ID
   - Contact your IT/Data team to get these credentials
   - Or create an App Registration in Azure Portal

2. Default Azure Credential - Uses environment/managed identity
   - Works if you're already logged into Azure CLI
   - Or if running on Azure (uses managed identity)
   - Set: az login (for Azure CLI)

3. Interactive Browser - For local development
   - Opens browser for you to sign in
   - Easiest for local testing
    """)
    
    auth_method = get_input("Choose method (1=Service Principal, 2=Default, 3=Interactive)", "3")
    
    azure_client_id = ""
    azure_client_secret = ""
    azure_tenant_id = ""
    
    if auth_method == "1":
        print("\n" + "=" * 60)
        print("Service Principal Configuration")
        print("=" * 60)
        print("""
You'll need to get these from your IT/Data team or Azure Portal:

1. Azure Tenant ID: Your organization's Azure AD tenant ID
2. Azure Client ID: Application (client) ID of the service principal
3. Azure Client Secret: Secret value for the service principal

Contact your Databricks administrator or IT team for these values.
        """)
        
        azure_tenant_id = get_input("Enter Azure Tenant ID")
        azure_client_id = get_input("Enter Azure Client ID")
        azure_client_secret = get_input("Enter Azure Client Secret", secret=True)
    
    print("\n" + "=" * 60)
    print("STEP 4: Configure Catalog and Schema")
    print("=" * 60)
    print("""
Catalog and Schema specify which database/schema to use by default.

Common values:
   - Catalog: "hive_metastore" (default) or a Unity Catalog name
   - Schema: "default" (default) or a specific schema name

You can change these later or specify them in queries.
    """)
    
    catalog = get_input("Enter catalog name", "hive_metastore")
    schema = get_input("Enter schema name", "default")
    
    print("\n" + "=" * 60)
    print("Configuration Summary")
    print("=" * 60)
    print(f"Server Hostname: {server_hostname}")
    print(f"HTTP Path: {http_path}")
    print(f"Authentication: Azure AD")
    if auth_method == "1":
        print(f"Tenant ID: {azure_tenant_id}")
        print(f"Client ID: {azure_client_id}")
        print(f"Client Secret: {'*' * 20} (hidden)")
    elif auth_method == "2":
        print("Method: Default Azure Credential (environment/managed identity)")
    else:
        print("Method: Interactive Browser")
    print(f"Catalog: {catalog}")
    print(f"Schema: {schema}")
    
    confirm = input("\nSave this configuration? (y/n): ").strip().lower()
    
    if confirm == 'y':
        # Create .env file
        env_content = f"""# JLL EDP Databricks Configuration (Azure AD)
# Generated by configure_connection_azure.py

DATABRICKS_SERVER_HOSTNAME={server_hostname}
DATABRICKS_HTTP_PATH={http_path}
DATABRICKS_USE_AZURE_AD=true
DATABRICKS_CATALOG={catalog}
DATABRICKS_SCHEMA={schema}
"""
        
        if auth_method == "1":
            env_content += f"""
# Azure AD Service Principal (for automated scripts)
AZURE_TENANT_ID={azure_tenant_id}
AZURE_CLIENT_ID={azure_client_id}
AZURE_CLIENT_SECRET={azure_client_secret}
"""
        elif auth_method == "2":
            env_content += """
# Using Default Azure Credential
# Make sure you're logged in: az login
# Or configure managed identity if running on Azure
"""
        else:
            env_content += """
# Using Interactive Browser authentication
# Will prompt for sign-in when connecting
"""
        
        env_file = ".env"
        try:
            with open(env_file, 'w') as f:
                f.write(env_content)
            print(f"\n✓ Configuration saved to {env_file}")
            print("✓ This file is in .gitignore and won't be committed to version control")
        except Exception as e:
            print(f"\n✗ Error saving configuration: {e}")
            print("\nYou can manually create a .env file with:")
            print(env_content)
            return False
        
        print("\n" + "=" * 60)
        print("Next Steps")
        print("=" * 60)
        print("""
1. Install dependencies:
   pip3 install -r requirements.txt

2. If using Default Azure Credential, log in:
   az login

3. Test your connection:
   python3 edp_connection.py

4. Start querying:
   python3 example_usage.py
        """)
        
        return True
    else:
        print("\nConfiguration not saved. You can run this script again.")
        return False

if __name__ == "__main__":
    try:
        configure_connection()
    except KeyboardInterrupt:
        print("\n\nConfiguration cancelled.")
        sys.exit(0)

