import sys
from pathlib import Path

for _p in Path(__file__).resolve().parents:
    if (_p / "repo_paths.py").is_file():
        if str(_p) not in sys.path:
            sys.path.insert(0, str(_p))
        break
else:
    raise RuntimeError("Not inside project Python tree")
from repo_paths import repo_root

PROJECT_ROOT = repo_root()

"""
Interactive script to help configure your Databricks connection
"""

import os
import sys

def get_input(prompt, default=None, secret=False):
    """Get user input with optional default value"""
    if default:
        prompt_text = f"{prompt} [{default}]: "
    else:
        prompt_text = f"{prompt}: "
    
    if secret:
        import getpass
        value = getpass.getpass(prompt_text)
    else:
        value = input(prompt_text).strip()
    
    return value if value else default

def configure_connection():
    """Interactive configuration helper"""
    print("=" * 60)
    print("JLL EDP Databricks Connection Configuration")
    print("=" * 60)
    print("\nThis script will help you configure your Databricks connection.")
    print("You'll need to gather some information from your Databricks workspace.\n")
    
    input("Press Enter to continue...")
    
    print("\n" + "=" * 60)
    print("STEP 1: Find Your Server Hostname")
    print("=" * 60)
    print("""
1. Open your Databricks workspace in a web browser
2. Look at the URL in your browser's address bar
3. The server hostname is the domain part of the URL

Examples:
   - If URL is: https://adb-1234567890123456.7.azuredatabricks.net
     Server hostname is: adb-1234567890123456.7.azuredatabricks.net
   
   - If URL is: https://your-workspace.cloud.databricks.com
     Server hostname is: your-workspace.cloud.databricks.com
    """)
    
    server_hostname = get_input("Enter your Databricks server hostname")
    
    print("\n" + "=" * 60)
    print("STEP 2: Find Your HTTP Path")
    print("=" * 60)
    print("""
1. In your Databricks workspace, click "SQL Warehouses" in the left sidebar
2. Click on your SQL Warehouse (or create one if you don't have one)
3. Click the "Connection details" tab
4. Copy the "HTTP path" value

Example: /sql/1.0/warehouses/abc123def456ghi789
    """)
    
    http_path = get_input("Enter your HTTP path")
    
    print("\n" + "=" * 60)
    print("STEP 3: Get Your Access Token")
    print("=" * 60)
    print("""
1. Click your user icon (top right corner)
2. Go to "User Settings"
3. Click "Access Tokens" tab
4. Click "Generate New Token"
5. Give it a name (e.g., "EDP Connection")
6. Set expiration (optional, or leave default)
7. Click "Generate"
8. COPY THE TOKEN IMMEDIATELY - you won't see it again!
    """)
    
    access_token = get_input("Enter your access token", secret=True)
    
    print("\n" + "=" * 60)
    print("STEP 4: Configure Catalog and Schema")
    print("=" * 60)
    print("""
Catalog and Schema specify which database/schema to use by default.

Common values:
   - Catalog: "hive_metastore" (default) or a Unity Catalog name
   - Schema: "default" (default) or a specific schema name

You can change these later or specify them in queries.
    """)
    
    catalog = get_input("Enter catalog name", "hive_metastore")
    schema = get_input("Enter schema name", "default")
    
    print("\n" + "=" * 60)
    print("Configuration Summary")
    print("=" * 60)
    print(f"Server Hostname: {server_hostname}")
    print(f"HTTP Path: {http_path}")
    print(f"Access Token: {'*' * 20} (hidden)")
    print(f"Catalog: {catalog}")
    print(f"Schema: {schema}")
    
    confirm = input("\nSave this configuration? (y/n): ").strip().lower()
    
    if confirm == 'y':
        # Create .env file
        env_content = f"""# JLL EDP Databricks Configuration
# Generated by configure_connection.py

DATABRICKS_SERVER_HOSTNAME={server_hostname}
DATABRICKS_HTTP_PATH={http_path}
DATABRICKS_ACCESS_TOKEN={access_token}
DATABRICKS_CATALOG={catalog}
DATABRICKS_SCHEMA={schema}
"""
        
        env_file = ".env"
        try:
            with open(env_file, 'w') as f:
                f.write(env_content)
            print(f"\n✓ Configuration saved to {env_file}")
            print("✓ This file is in .gitignore and won't be committed to version control")
        except Exception as e:
            print(f"\n✗ Error saving configuration: {e}")
            print("\nYou can manually create a .env file with:")
            print(env_content)
            return False
        
        # Also update the edp_connection.py with defaults
        print("\nWould you like to also update edp_connection.py with these as defaults?")
        update_defaults = input("(This is optional - .env file will be used anyway) (y/n): ").strip().lower()
        
        if update_defaults == 'y':
            try:
                # Read current file
                with open('edp_connection.py', 'r') as f:
                    content = f.read()
                
                # Update defaults
                content = content.replace(
                    '"server_hostname": os.getenv("DATABRICKS_SERVER_HOSTNAME", "your-workspace.cloud.databricks.com")',
                    f'"server_hostname": os.getenv("DATABRICKS_SERVER_HOSTNAME", "{server_hostname}")'
                )
                content = content.replace(
                    '"http_path": os.getenv("DATABRICKS_HTTP_PATH", "/sql/1.0/warehouses/your-warehouse-id")',
                    f'"http_path": os.getenv("DATABRICKS_HTTP_PATH", "{http_path}")'
                )
                content = content.replace(
                    '"catalog": os.getenv("DATABRICKS_CATALOG", "hive_metastore")',
                    f'"catalog": os.getenv("DATABRICKS_CATALOG", "{catalog}")'
                )
                content = content.replace(
                    '"schema": os.getenv("DATABRICKS_SCHEMA", "default")',
                    f'"schema": os.getenv("DATABRICKS_SCHEMA", "{schema}")'
                )
                
                with open('edp_connection.py', 'w') as f:
                    f.write(content)
                
                print("✓ Updated edp_connection.py with defaults")
            except Exception as e:
                print(f"✗ Error updating edp_connection.py: {e}")
        
        print("\n" + "=" * 60)
        print("Next Steps")
        print("=" * 60)
        print("""
1. Install dependencies:
   pip3 install -r requirements.txt

2. Test your connection:
   python3 edp_connection.py

3. Start querying:
   python3 example_usage.py
        """)
        
        return True
    else:
        print("\nConfiguration not saved. You can run this script again.")
        return False

if __name__ == "__main__":
    try:
        configure_connection()
    except KeyboardInterrupt:
        print("\n\nConfiguration cancelled.")
        sys.exit(0)

